### PR TITLE
165: standardize zd names

### LINKED ISSUE #165: Refactor: Standardize zoning-district and zoning-district-class names
# Description

Update the variable, function, method, and operationIds to follow #115 

## Acceptance criteria
1. Names are updated in:
- Open API documentation
  - [x] operation Ids
  - [x] path parameters
  - [x] misc variables 
- Method names
  - [x] Controller
  - [x] Service
  - [x] Repo 
- Parameter names
  - [x] Controller
  - [x] Service
  - [x] Repo
 - Test descriptions
   - [x] e2e
   - [x] service unit

2. OpenAPI documenation page is rebuilt:
```
npm run redoc:build
```
3. Kubb is regenerated
```
npm run generate
```
## Related
Blocked by #150  #151 #152 #153 #154

### PR DESCRIPTION
**Pull request by TangoYankee**
standardize names for zoning district and zoning district class domains

closes #165

### CODE REVIEW

**Review by horatiorosa — DISMISSED** [review]
LGTM.

The standardized names look good and make sense but I didn't fully appreciate the length some name would reach.

I did not review anything in the`src/gen` folder.

I think @pratishta should take a look at this PR as well.

**Comment by TylerMatteo** [comment]
Leaving my two cents - LGTM. The method names and operationIds are consistent with what we talked about in the [discussion](https://github.com/NYCPlanning/ae-zoning-api/discussions/115). To @horatiorosa's point, some of them do feel a little jarring now that I'm seeing how chonky they got in practice, but I still feel like it's the best decision.

The one that stood out to me is `findZoningDistrictByZoningDistrictId` because it feels like it's including the domain twice and could be shortened to `findZoningDistrictById`, but it makes sense when see it in in context next to ones like `findZoningDistrictClassesByZoningDistrictId`.

**Review by pratishta — APPROVED** [review]
🚀

**Review by horatiorosa — APPROVED** [review]
🚢

**Pull request merged**
